// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZL5yaF_sEnIVvS_8AioyuyfiC98TjKb4',
    appId: '1:16515346951:web:ff5068e8ce74a1b35b30a2',
    messagingSenderId: '16515346951',
    projectId: 'todolistapp-82d2c',
    authDomain: 'todolistapp-82d2c.firebaseapp.com',
    storageBucket: 'todolistapp-82d2c.firebasestorage.app',
    measurementId: 'G-K6DMX9DNFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ63guWQ71-FMHsBtK10NdnLhieNAbYUk',
    appId: '1:16515346951:android:087453be3ba877055b30a2',
    messagingSenderId: '16515346951',
    projectId: 'todolistapp-82d2c',
    storageBucket: 'todolistapp-82d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxNiMfqWo2vriV_-iYXH5pys74mr9YnwE',
    appId: '1:16515346951:ios:7e05c7b17faab1085b30a2',
    messagingSenderId: '16515346951',
    projectId: 'todolistapp-82d2c',
    storageBucket: 'todolistapp-82d2c.firebasestorage.app',
    iosBundleId: 'com.example.todolistapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxNiMfqWo2vriV_-iYXH5pys74mr9YnwE',
    appId: '1:16515346951:ios:7e05c7b17faab1085b30a2',
    messagingSenderId: '16515346951',
    projectId: 'todolistapp-82d2c',
    storageBucket: 'todolistapp-82d2c.firebasestorage.app',
    iosBundleId: 'com.example.todolistapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZL5yaF_sEnIVvS_8AioyuyfiC98TjKb4',
    appId: '1:16515346951:web:6c43bb453c375b3f5b30a2',
    messagingSenderId: '16515346951',
    projectId: 'todolistapp-82d2c',
    authDomain: 'todolistapp-82d2c.firebaseapp.com',
    storageBucket: 'todolistapp-82d2c.firebasestorage.app',
    measurementId: 'G-FQKVT0T00E',
  );
}
